version: "1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: volt1c/express-drive
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./dist:/code
